-- Migration: add device_id column to refresh_tokens
ALTER TABLE refresh_tokens
ADD COLUMN device_id varchar NULL;

-- Optionally add an index for efficient lookups by user + device
-- Use the actual FK column name generated by TypeORM (userId) and a normal index
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_device ON refresh_tokens ("userId", device_id);
