version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carwash-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: car_wash
      POSTGRES_DB: carwash_db
    ports:
      - '5436:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: carwash-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
